# Created with package:mono_repo v5.0.4
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: "analyze; PKG: example; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.5
      - id: example_pub_upgrade
        name: example; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example
        run: dart pub upgrade
      - name: example; dart analyze
        if: "always() && steps.example_pub_upgrade.conclusion == 'success'"
        working-directory: example
        run: dart analyze
  job_002:
    name: "analyze; PKG: example_dartmapper; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example_dartmapper;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:example_dartmapper
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.5
      - id: example_dartmapper_pub_upgrade
        name: example_dartmapper; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: example_dartmapper
        run: dart pub upgrade
      - name: example_dartmapper; dart analyze
        if: "always() && steps.example_dartmapper_pub_upgrade.conclusion == 'success'"
        working-directory: example_dartmapper
        run: dart analyze
